export const categories = [
  ['design','界面设计',['web','网页设计'],['mobile','移动界面'],['identity','品牌系统'],['design-system','设计系统']],
  ['frontend','前端开发',['implementation','界面实现'],['animation','交互动效']],
  ['backend','后端开发',['domain','领域与服务']],
  ['full-stack','全栈开发',['delivery','端到端交付']],
  ['architecture','架构设计',['modules','模块边界'],['modeling','领域建模'],['visualization','架构图']],
  ['quality','测试与调试',['testing','测试策略'],['debugging','故障诊断'],['verification','验收验证']],
  ['review','代码审查',['diff','变更审查'],['feedback','审查反馈'],['impact','影响分析']],
  ['devops','工程运维',['git','版本控制'],['tooling','工程工具']],
  ['security','安全分析',['data-flow','数据流安全'],['guardrails','操作约束']],
  ['research','搜索与研究',['search','联网检索'],['code','代码探索'],['sources','资料研究']],
  ['media','图片与视频',['generation','媒体生成'],['references','视觉参考']],
  ['collaboration','计划与协作',['planning','需求计划'],['orchestration','任务编排'],['writing','文档写作'],['learning','教学交流']]
].map(([id,title,...children])=>({id,title,children:children.map(([id,title])=>({id,title}))}));

const rows = {
  'design-taste-frontend':['design/web','根据品牌和内容设计有辨识度的落地页、作品集与重设计。','为摄影师制作作品集首页','HTML CSS React',''],
  'design-taste-frontend-v1':['design/web','复现 Taste 原版的布局、动效强度与视觉密度约定。','延续依赖 v1 风格的现有站点','HTML CSS React',''],
  'gpt-taste':['frontend/animation','用 GSAP 滚动动画、编辑式排版与 AIDA 结构实现视觉网站。','实现滚动叠层的品牌故事页面','GSAP JavaScript CSS','GSAP；Python（布局随机化）'],
  'image-to-code':['frontend/implementation','先生成分区设计图并分析，再将图像忠实实现为网页。','生成餐厅页面参考图并实现响应式界面','HTML CSS React','Agent 图像生成工具'],
  'imagegen-frontend-web':['media/references','为网页每个区块分别生成视觉参考并统一配色与叙事。','为八段式产品首页生成八张独立参考图','Web','Agent 图像生成工具'],
  'imagegen-frontend-mobile':['design/mobile','为 iOS、Android 与跨平台应用设计连贯的屏幕参考图。','生成阅读应用的列表、详情和设置页参考','iOS Android','Agent 图像生成工具'],
  'brandkit':['design/identity','生成品牌指南、标志系统与视觉应用展示板。','为开发者工具设计品牌识别展示板','Brand','Agent 图像生成工具'],
  'redesign-existing-projects':['design/web','审查现有网站视觉问题并在保留功能的前提下重设计。','改善已有商店的排版、间距和导航','CSS Tailwind React','现有项目源码'],
  'high-end-visual-design':['design/web','用字体、空间、阴影与动效细节构建精致网页视觉。','打磨精品酒店网站的视觉层次','CSS Motion',''],
  'full-output-enforcement':['collaboration/writing','约束代码输出完整度，避免占位符、省略与截断。','完整输出五个页面组件及其依赖','Agent',''],
  'minimalist-ui':['design/web','采用暖色单色、编辑式字体与扁平网格设计极简界面。','设计文档工作台的清晰首页','CSS',''],
  'industrial-brutalist-ui':['design/web','融合瑞士排版与机械终端视觉设计数据密集界面。','设计工业遥测仪表盘','CSS',''],
  'stitch-design-taste':['design/design-system','为 Google Stitch 编写包含字体、配色和布局规则的 DESIGN.md。','为产品原型建立 Stitch 视觉约定','Google-Stitch','Google Stitch'],
  'ui-ux-pro-max':['design/design-system','检索本地风格、字体、色板、图表与技术栈规范形成界面方案。','为医疗管理界面选择可访问的配色和表格规范','Python React Vue SwiftUI Flutter','Python 3'],
  'skillshelf-web-search':['research/search','直接调用 Tavily 或 Brave 搜索新信息、官方文档和可追溯资料。','比较两种数据库的官方备份方案并列出来源','Python Tavily Brave','Python 3.10+；Tavily 或 Brave 凭据及网络'],
  'skillshelf-media-generation':['media/generation','在本机调用服务商生成和编辑图片、生成视频并保存任务与成品。','以参考图生成短视频并记录可恢复的任务号','Python Image Video','Python 3.10+；服务商凭据、模型权限、额度及网络'],
  'archify':['architecture/visualization','将系统架构、调用时序或状态流程制作成可探索的独立 HTML 图。','绘制登录请求从浏览器到数据库的时序图','HTML SVG Mermaid','浏览器；可选截图和导出工具'],
  'ask-matt':['collaboration/orchestration','根据工程情境选择 Matt 技能及从想法到交付的工作流程。','判断当前需求应先访谈还是直接实现','Agent','Matt 包内关联技能'],
  'code-review':['review/diff','从代码规范与原始需求两个维度审查指定基线以来的变更。','审查相对 main 的实现是否符合验收条件','Git','Git；支持并行审查的 Agent'],
  'codebase-design':['architecture/modules','用深模块原则确定接口、职责边界和可测试的接缝。','重新设计缓存模块的小接口','Language-agnostic','项目源码'],
  'diagnosing-bugs':['quality/debugging','通过复现、证据与假设验证诊断复杂错误和性能回退。','定位请求偶发超时的根因','Language-agnostic','可复现问题及诊断工具'],
  'domain-modeling':['architecture/modeling','澄清领域术语和边界，并将决策记录到 CONTEXT.md 与 ADR。','统一订单取消和退款的业务语义','Domain-model','项目领域资料'],
  'grill-with-docs':['collaboration/planning','通过持续访谈完善设计，并同步建立领域词汇与决策文档。','访谈新的权限系统并记录 ADR','Agent','grilling；domain-modeling'],
  'implement':['full-stack/delivery','依据规格或任务单完成实现，并进行类型检查、测试和审查。','按规格交付包含界面与接口的任务','Language-agnostic','项目构建测试工具；tdd；code-review'],
  'improve-codebase-architecture':['architecture/modules','扫描浅模块与边界问题，输出 HTML 改进报告并讨论选定方案。','找出业务服务中可合并的透传接口','HTML','项目源码；codebase-design'],
  'prototype':['collaboration/planning','制作可丢弃原型来回答状态模型、业务逻辑或视觉设计问题。','用单文件交互原型验证队列状态转换','HTML JavaScript','浏览器'],
  'research':['research/sources','根据官方文档、源码和规范研究问题并记录带来源的结论。','核实某 SDK 的重试语义','Markdown','一手资料访问；Agent 后台任务'],
  'resolving-merge-conflicts':['devops/git','结合双方提交意图和原始需求解决 Git 合并或变基冲突。','保留两个分支的独立业务修复','Git','存在冲突的 Git 工作区'],
  'setup-matt-pocock-skills':['devops/tooling','配置问题跟踪器、分诊标签和领域文档布局供 Matt 工程流程使用。','为仓库配置本地任务单与 ADR 目录','Git GitHub Markdown','仓库写入权限'],
  'tdd':['quality/testing','以红绿重构循环编写测试，从公共接口验证行为。','先写失败测试再实现库存扣减','Language-agnostic','项目测试运行器'],
  'to-spec':['collaboration/planning','将已有讨论综合成需求规格并提交到已配置的任务系统。','把讨论好的登录需求整理成验收规格','Markdown GitHub','已配置问题跟踪器；发布需授权'],
  'to-tickets':['collaboration/planning','将需求规格拆成有依赖关系、可独立实施的任务单。','把权限系统规格拆成可交付任务','Markdown GitHub','需求规格与问题跟踪器'],
  'triage':['collaboration/planning','调查问题或外部拉取请求并转化为 Agent 可执行的简报。','分诊用户反馈的上传失败问题','Git GitHub','问题跟踪器与仓库证据'],
  'wayfinder':['collaboration/planning','把跨会话的大型工作规划为任务系统中的决策地图，逐项澄清未知问题。','将大型迁移的待定方案整理为决策任务','Markdown GitHub','问题跟踪器；setup-matt-pocock-skills'],
  'wizard':['devops/tooling','为只有用户能执行的配置步骤生成交互式 Bash 向导。','引导用户在服务商后台创建并配置 CI 凭据','Bash GitHub','Bash；用户参与；凭据配置授权'],
  'claude-handoff':['collaboration/orchestration','为 Claude 后续会话整理工程任务的上下文和接续信息。','将未完成的重构交接给下一会话','Claude-Code','Claude Code'],
  'implement-spec':['full-stack/delivery','将完整规格组织为任务图并在同一分支实施与验证。','按完整规格交付前后端协作功能','Git','需求规格与测试工具'],
  'loop-me':['collaboration/planning','通过多轮会话构建可实施的工作流规格。','逐步明确导入任务的重试与恢复流程','Markdown','持续的需求上下文'],
  'pr':['devops/git','整理已完成变更并准备可审查的拉取请求。','为功能分支撰写问题、行为和验证说明','Git GitHub','Git；发布拉取请求需授权'],
  'retro':['collaboration/planning','复盘实施过程中的阻碍和经验，提炼后续改进。','复盘一次失败的数据库迁移演练','Markdown','本次任务过程记录'],
  'setup-ts-deep-modules':['architecture/modules','为 TypeScript 项目配置深模块约定与工程支撑。','规范 TypeScript 模块公共接口','TypeScript','TypeScript 项目'],
  'writing-beats':['collaboration/writing','通过关键叙事节拍组织写作内容。','为技术文章安排论证节奏','Markdown','写作主题与素材'],
  'writing-fragments':['collaboration/writing','从写作片段整理素材并逐步形成文本。','把研究笔记整理成可复用的文章片段','Markdown','原始笔记'],
  'writing-shape':['collaboration/writing','确定文章的整体结构和论述形状。','设计一篇架构决策说明的组织顺序','Markdown','写作目的与受众'],
  'git-guardrails-claude-code':['security/guardrails','为 Claude Code 的 Git 操作建立安全护栏。','防止自动化会话执行破坏性 Git 操作','Git Claude-Code','Claude Code；配置写入授权'],
  'migrate-to-shoehorn':['devops/tooling','将适用的类型转换代码迁移到 shoehorn 的约定。','统一 TypeScript 测试中的类型构造','TypeScript','shoehorn；TypeScript 项目'],
  'scaffold-exercises':['collaboration/learning','为教学主题创建可实践的编程练习结构。','搭建 TypeScript 泛型练习','TypeScript','项目教学环境'],
  'setup-pre-commit':['devops/tooling','配置提交前自动检查以减少格式和质量问题。','在提交前运行 lint 与类型检查','Git','项目校验工具；Git hook 写入授权'],
  'grill-me':['collaboration/planning','持续追问需求中的假设、边界与未明确决策。','明确通知系统的投递与撤回语义','Agent','用户需求背景'],
  'grilling':['collaboration/planning','使用系统化访谈逐项澄清设计取舍。','审视缓存失效策略的边界条件','Agent','待讨论的方案'],
  'handoff':['collaboration/orchestration','将当前进度、决策和待办交接给后续协作者。','为下一位维护者整理调查线索','Markdown','当前任务记录'],
  'teach':['collaboration/learning','围绕学习目标规划教学并记录学习进度。','建立面向实际项目的数据库学习计划','Markdown','学习目标与背景'],
  'to-questionnaire':['collaboration/planning','把无法独立回答的决策整理成面向知情人的问卷。','向运维团队确认备份窗口和恢复目标','Markdown','问卷受众与所需决策'],
  'wait-what':['collaboration/learning','用简明语言和领域词汇重新解释难以理解的结论。','重新说明状态机设计的来龙去脉','Agent','待解释的内容'],
  'writing-for-agents':['collaboration/writing','为技能、AGENTS.md 和相关文档编写可执行、可预测的说明。','重写仓库 Agent 指引以减少歧义','Markdown','Agent 指引与技能机制'],
  'brainstorming':['collaboration/planning','在设计和实现前澄清意图、约束与候选方案。','讨论新导出功能的使用场景与验收条件','Agent','需求背景'],
  'diagnosing-superpowers':['quality/debugging','通过会话记录诊断 Superpowers 流程偏差与重复工作。','找出技能未触发或任务耗时异常的原因','Agent','可访问且已脱敏的会话记录'],
  'dispatching-parallel-agents':['collaboration/orchestration','为互不依赖的调查或实现任务分派独立 Agent。','并行调查三个互不相关的测试失败','Agent','支持子 Agent 的宿主；用户授权'],
  'executing-plans':['collaboration/orchestration','在当前会话按既定计划逐项实施并进行整体验证。','顺序执行已批准的模块迁移计划','Agent','已批准实施计划'],
  'finishing-a-development-branch':['devops/git','在测试通过后评估分支集成、审查与收尾方式。','为已完成的分支选择合并或拉取请求流程','Git','通过的测试与集成授权'],
  'receiving-code-review':['review/feedback','验证审查意见的技术依据并逐项处理反馈。','核实审阅者提出的并发缺陷再修复','Git','代码审查意见'],
  'requesting-code-review':['review/diff','为审阅者准备明确范围与上下文并发起代码审查。','审查大型实现是否符合原始计划','Agent Git','可调用审阅 Agent'],
  'subagent-driven-development':['full-stack/delivery','按独立任务分派实现与审查 Agent 完成已批准计划。','通过逐任务审查交付跨前后端功能','Agent Git','子 Agent 能力；已批准计划'],
  'systematic-debugging':['quality/debugging','先收集证据并找到根因，再选择修复与回归验证。','定位构建错误与异常行为的共同原因','Language-agnostic','可复现故障与诊断环境'],
  'test-driven-development':['quality/testing','通过失败测试驱动最小实现并持续重构。','修复解析边界条件并保留回归测试','Language-agnostic','项目测试运行器'],
  'using-git-worktrees':['devops/git','为独立功能创建并核验隔离的 Git 工作区。','在不影响当前修改的情况下实施新任务','Git','Git worktree 支持'],
  'using-superpowers':['collaboration/orchestration','在任务开始时识别适用技能并按宿主工具调用。','为复杂实现选择正确的技能流程','Agent','宿主技能调用能力'],
  'verification-before-completion':['quality/verification','要求完成声明由新鲜的测试和实际执行证据支持。','在宣布修复前重新运行相关回归检查','Language-agnostic','可执行验证命令'],
  'writing-plans':['collaboration/planning','将规格拆为包含文件、实现步骤与验证命令的实施计划。','为缓存重构编写可逐项执行的计划','Markdown','已确认规格与仓库上下文'],
  'writing-skills':['collaboration/writing','以行为验证方法创建、修订并验证 Agent 技能说明。','测试技能指令是否能在真实任务中触发','Markdown Agent','技能测试环境；同包 using-superpowers 引用'],
  'gitnexus-cli':['devops/tooling','操作 GitNexus 索引、状态、清理和 wiki 生成命令。','为仓库建立可查询代码图谱','GitNexus Node.js','另行安装 GitNexus CLI'],
  'gitnexus-debugging':['quality/debugging','借助调用图与代码证据定位错误来源。','追踪返回 500 的接口调用链','GitNexus','GitNexus MCP 与新鲜索引'],
  'gitnexus-exploring':['research/code','通过图谱探索陌生仓库的模块与执行流程。','解释认证请求经过的组件','GitNexus','GitNexus MCP 与新鲜索引'],
  'gitnexus-guide':['research/code','查询 GitNexus 工具、图谱模式和资源的使用方式。','选择适合依赖关系问题的图谱查询','GitNexus','GitNexus MCP'],
  'gitnexus-impact-analysis':['review/impact','分析符号变更的调用方与回归影响范围。','检查修改公共函数会影响哪些入口','GitNexus','GitNexus MCP 与新鲜索引'],
  'gitnexus-lfg':['full-stack/delivery','编排图谱驱动的计划、执行门禁和最终审查流程。','从计划到审查交付一次功能变更','GitNexus Git','GitNexus 运行时；plan/work/review 成员'],
  'gitnexus-pdg-query':['security/data-flow','查询控制与数据依赖以解释语句守卫和变量传播。','确认危险调用是否受权限判断保护','GitNexus PDG','启用 --pdg 的 GitNexus 索引'],
  'gitnexus-plan':['collaboration/planning','结合图谱、语句依赖与源码证据编写可实施工程计划。','为重试机制生成包含测试场景的计划','GitNexus','GitNexus MCP 与新鲜索引'],
  'gitnexus-refactoring':['architecture/modules','依据引用图安全地重命名、提取、拆分或移动代码。','拆分服务模块并确认全部调用方','GitNexus Git','GitNexus MCP 与新鲜索引'],
  'gitnexus-review':['review/diff','利用结构证据审查 PR、分支或本地差异的缺陷与回归。','评估拉取请求的测试缺口和合并风险','GitNexus Git','GitNexus 运行时；可读代码差异'],
  'gitnexus-taint-analysis':['security/data-flow','分析 CFG、污点和跨过程数据流中的源到汇传播。','追踪用户输入流入危险 API 的路径','GitNexus PDG','启用 --pdg 的 GitNexus 索引'],
  'gitnexus-work':['full-stack/delivery','按图谱计划实施变更并在符号编辑前检查影响、完成测试。','实施已批准的 ingestion 重试计划','GitNexus Git','GitNexus 运行时；已批准计划'],
  'gitnexus-pr-swarm-review':['review/diff','协调多个审阅视角评估 GitNexus PR 的生产就绪程度。','对 GitNexus 的重大 PR 执行综合审查','GitNexus Claude-Code','Claude Code 子 Agent；GitNexus 项目']
};

export function curatedMetadata(name) {
  const row=rows[name];if(!row)throw new Error('Missing individually curated member: '+name);
  const [classification,description,example,stack,dependencies]=row;
  const [category,subcategory]=classification.split('/');
  return {category,subcategory,description,useWhen:example+'时使用；'+description,purpose:description,examples:[example],stack:stack.split(' ').filter(Boolean),dependencies:dependencies.split('；').filter(Boolean)};
}
